{
	"id": "CVE-2023-50782",
	"sourceIdentifier": "secalert@redhat.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-02-05T21:15:11.183",
	"lastModified": "2024-02-06T01:00:55.997",
	"descriptions": [
		{
			"lang": "en",
			"value": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data."
		}
	],
	"references": [
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/security/cve/CVE-2023-50782"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2254432"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "secalert@redhat.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
					"attackVector": "NETWORK",
					"attackComplexity": "HIGH",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "HIGH",
					"integrityImpact": "NONE",
					"availabilityImpact": "NONE",
					"baseScore": 5.9,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 2.2,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "secalert@redhat.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-208"
				}
			]
		}
	]
}
