{
	"id": "CVE-2023-46960",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-04-29T21:15:47.527",
	"lastModified": "2024-08-01T13:45:04.950",
	"descriptions": [
		{
			"lang": "en",
			"value": "Buffer Overflow vulnerability in PyPXE v.1.8.4 allows a remote attacker to cause a denial of service via the handle function in the tftp module."
		},
		{
			"lang": "es",
			"value": "Vulnerabilidad de desbordamiento de búfer en PyPXE v.1.8.4 permite que un atacante remoto provoque una denegación de servicio a través de la función de manejo en el módulo tftp."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/pypxe/PyPXE/issues/206"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "LOW",
					"integrityImpact": "LOW",
					"availabilityImpact": "HIGH",
					"baseScore": 8.6,
					"baseSeverity": "HIGH"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 4.7
			}
		]
	},
	"weaknesses": [
		{
			"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-120"
				}
			]
		}
	]
}
