{
	"id": "CVE-2023-39661",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Analyzed",
	"published": "2023-08-15T17:15:13.133",
	"lastModified": "2023-08-22T17:32:14.513",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"tags": [
				"Exploit",
				"Issue Tracking",
				"Third Party Advisory"
			],
			"url": "https://github.com/gventuri/pandas-ai/issues/410"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "nvd@nist.gov",
				"type": "Primary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "HIGH",
					"integrityImpact": "HIGH",
					"availabilityImpact": "HIGH",
					"baseScore": 9.8,
					"baseSeverity": "CRITICAL"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 5.9
			}
		]
	},
	"weaknesses": [
		{
			"source": "nvd@nist.gov",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-74"
				}
			]
		}
	],
	"configurations": [
		{
			"nodes": [
				{
					"operator": "OR",
					"cpeMatch": [
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:gabrieleventuri:pandasai:*:*:*:*:*:python:*:*",
							"matchCriteriaId": "B20DF392-01BD-403C-B22F-54FD7BF3841F",
							"versionEndIncluding": "0.9.1"
						}
					]
				}
			]
		}
	]
}
