{
	"id": "CVE-2024-53432",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-11-21T18:15:14.420",
	"lastModified": "2024-11-21T18:15:14.420",
	"descriptions": [
		{
			"lang": "en",
			"value": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files."
		},
		{
			"lang": "es",
			"value": "Al analizar ciertos archivos PLY malformados, la versión 1.14.1 de PCL se bloquea debido a una excepción std::out_of_range no detectada en PCLPointCloud2::at. Este problema podría aprovecharse para provocar un ataque de denegación de servicio (DoS) al procesar archivos PLY que no son de confianza."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/PointCloudLibrary/pcl/issues/6162"
		}
	],
	"metrics": {}
}
