{
	"id": "CVE-2024-39614",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Received",
	"published": "2024-07-10T05:15:12.237",
	"lastModified": "2024-07-10T05:15:12.237",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en Django 5.0 anterior a 5.0.7 y 4.2 anterior a 4.2.14. get_supported_language_variant() estaba sujeto a un posible ataque de denegación de servicio cuando se usaba con cadenas muy largas que contenían caracteres específicos."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://docs.djangoproject.com/en/dev/releases/security/"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://groups.google.com/forum/#%21forum/django-announce"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
		}
	],
	"metrics": {}
}
