{
	"id": "CVE-2024-1141",
	"sourceIdentifier": "secalert@redhat.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-02-01T15:15:08.547",
	"lastModified": "2024-02-01T21:30:44.493",
	"descriptions": [
		{
			"lang": "en",
			"value": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled."
		}
	],
	"references": [
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/security/cve/CVE-2024-1141"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2258836"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "secalert@redhat.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
					"attackVector": "LOCAL",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "HIGH",
					"integrityImpact": "NONE",
					"availabilityImpact": "NONE",
					"baseScore": 5.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 1.8,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "secalert@redhat.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-779"
				}
			]
		}
	]
}
