{
	"id": "CVE-2024-7958",
	"sourceIdentifier": "cna@python.org",
	"vulnStatus": "Rejected",
	"published": "2024-08-19T20:15:08.907",
	"lastModified": "2024-08-19T20:15:08.907",
	"descriptions": [
		{
			"lang": "en",
			"value": "Rejected reason: This CVE ID has been rejected or withdrawn by its CVE Numbering Authority."
		}
	],
	"references": [],
	"metrics": {}
}
